import { useEffect, useState } from "react";
import { Maximize2, X } from "lucide-react";
import exterior from "@/assets/property-exterior.png";
import room from "@/assets/mountain-room.png";
import bath from "@/assets/bathroom.png";
import verandah from "@/assets/verandah.png";
import common from "@/assets/common-room.png";
import cozy from "@/assets/cozy-room.png";
import windowView from "@/assets/window-view.png";
import bright from "@/assets/bright-room.png";
import lounge from "@/assets/mountain-lounge.png";
import corridor from "@/assets/gallery-corridor.png";

function GalleryButton({src,alt,className,onOpen}:{src:string;alt:string;className:string;onOpen:()=>void}) { return <button type="button" onClick={onOpen} className={`group relative overflow-hidden ${className}`} aria-label={`Enlarge ${alt}`}><img src={src} alt={alt} className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-105"/><span className="absolute bottom-4 right-4 grid h-10 w-10 place-items-center rounded-full bg-background/90 text-foreground opacity-0 backdrop-blur-md transition-opacity group-hover:opacity-100"><Maximize2 size={17}/></span></button> }
export function GalleryLightbox(){const [selected,setSelected]=useState<{src:string;alt:string}|null>(null);useEffect(()=>{if(!selected)return;const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setSelected(null)};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[selected]);return <><div className="grid auto-rows-[14rem] grid-cols-2 gap-3 md:auto-rows-[19rem] md:grid-cols-4"><GalleryButton src={exterior} alt="The District Green exterior at night" className="col-span-2 row-span-2" onOpen={()=>setSelected({src:exterior,alt:"The District Green exterior at night"})}/><GalleryButton src={room} alt="Guest room with mountain view" className="row-span-2" onOpen={()=>setSelected({src:room,alt:"Guest room with mountain view"})}/><GalleryButton src={bath} alt="Guest bathroom" className="" onOpen={()=>setSelected({src:bath,alt:"Guest bathroom"})}/><GalleryButton src={verandah} alt="Blue and wood verandah" className="" onOpen={()=>setSelected({src:verandah,alt:"Blue and wood verandah"})}/><GalleryButton src={common} alt="Spacious common area" className="col-span-2" onOpen={()=>setSelected({src:common,alt:"Spacious common area"})}/><GalleryButton src={cozy} alt="Cozy guest room" className="row-span-2" onOpen={()=>setSelected({src:cozy,alt:"Cozy guest room"})}/><GalleryButton src={windowView} alt="Mountain view from a guest room" className="row-span-2" onOpen={()=>setSelected({src:windowView,alt:"Mountain view from a guest room"})}/><GalleryButton src={bright} alt="Bright guest room" className="col-span-2" onOpen={()=>setSelected({src:bright,alt:"Bright guest room"})}/><GalleryButton src={lounge} alt="Mountain panorama from the lounge" className="col-span-2 row-span-2" onOpen={()=>setSelected({src:lounge,alt:"Mountain panorama from the lounge"})}/><GalleryButton src={corridor} alt="Sunlit homestay corridor" className="col-span-2 row-span-2" onOpen={()=>setSelected({src:corridor,alt:"Sunlit homestay corridor"})}/></div>{selected&&<div role="dialog" aria-modal="true" aria-label="Fullscreen photograph" className="fixed inset-0 z-[70] grid place-items-center bg-forest/95 p-4 md:p-10" onClick={()=>setSelected(null)}><button type="button" onClick={()=>setSelected(null)} className="absolute right-5 top-5 grid h-12 w-12 place-items-center rounded-full bg-background text-foreground" aria-label="Close photograph"><X/></button><img src={selected.src} alt={selected.alt} className="max-h-full max-w-full object-contain" onClick={(event)=>event.stopPropagation()}/></div>}</>}
